config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  post '/users' => 'users#create'
  resources :users do
    resources :articles
    member do
      get :confirm_email
    end
  end
   get "/articles/:article_id/comments/new" => "comments#new"
   post "/articles/:article_id/comments"   => "comments#create" , as: 'article_comments'
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :foreign_key => :article_id
  validates :title,  :presence => true
  validates :body,  :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :articles
  has_many :comments, :foreign_key => :user_id
  has_attached_file :cover_photo, :styles => { :medium => "840x375#", :large => "1920x1240#" }, :default_url => '/images/Profile/default_image.jpg'
  validates_attachment_content_type :cover_photo, content_type: /\Aimage\/.*\Z/
  before_create :confirmation_token
  validates :cover_photo, presence: true,  on: :update
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
            uniqueness: true,
            format: {
                with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end

  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :current_user
  private
  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @user = find_user(params[:user_id]) if !params["user_id"].blank?
    @articles = Article.all
  end

  def new
    @user = find_user(params[:user_id]) if !params["user_id"].blank?
    @article = Article.new
  end

  def create
    user_id = params[:user_id]
    @article = Article.new(article_params)
    @article.user_id = params[:user_id]
    if @article.save
      flash[:success] = "Article Created Successfully"
      redirect_to user_articles_path(user_id)
    else
      render :new
    end
  end

  def edit
    @user = find_user(params[:user_id]) if !params["user_id"].blank?
    @article = Article.find(params["id"])
  end

  def update
    @article = Article.find(params["id"])
    if @article.update(article_params)
      flash[:success] = "Article updated Successfully"
      redirect_to user_articles_path(params["user_id"])
    else
      render action: 'edit'
    end
  end

  def show
    @article = Article.find_by_id(params["id"])
    @comments = @article.comments
    respond_to do |format|
      #format.html # show.html.erb
      format.js # show.js.erb
    end
  end

  def destroy
    @article = Article.find_by_id(params["id"])
    @article.destroy
    redirect_to user_articles_path(params["user_id"])
  end

  private

  def find_user(id)
    user = User.find_by_id(id)
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @article = Article.find_by_id(params["article_id"])
    @user_id = params["user_id"]
    @comment = Comment.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    if @comment.save
      flash[:success] = "Comment Created"
      redirect_to user_articles_path(params[:comment][:user_id])
    else
      respond_to do |format|
        format.js  render :new
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      if user.email_confirmed
        session[:user_id] = user.id
        flash[:success] = 'Logged In!'
        redirect_to user_articles_path(user.id)
      else
        flash[:error] = 'Please activate your account by following the
        instructions in the account confirmation email you received to proceed'
      render :new
      end
    else
      flash[:error] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def show
     @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
         UserMailer.delay.registration_confirmation(@user)
         flash[:success] = "Welcome! Please confirm your email address to continue"
         redirect_to root_path
      else
         render :new
      end
  end

  def edit
    flash = Array.new
    @user = User.find_by_id(params["id"])
  end

  def update
    @user = User.find_by_id(params["id"])
    if params["user"].present?
    @user.update_attribute(:cover_photo, params["user"]["cover_photo"])
    redirect_to user_articles_path(@user.id)
    else
      flash[:error] = "please upload a valid file"
      render :edit
    end
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      flash[:success] = "Welcome to the User Blog! Your email has been confirmed.
      Please sign in to continue."
      redirect_to login_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-body">
      <table class="table table-striped">
        <tr>
          <th><h4>Details of Article</h4></th>
          <th></th>
        </tr>
        <tr>
          <td>
            <h5 class="panel-title">
              Title
            </h5>
          </td>
          <td>
            <%= article.title%>
          </td>
        </tr>
        <tr>
          <td>
            <h5 class="panel-title">
              Article Body
            </h5>
          </td>
          <td>
            <%= article.body%>
          </td>
        </tr>
      </table>
     <% unless @comments.blank? %>
      <table class="table table-striped">
        <tr>
          <th><h4>Comments List</h4></th>
          <th></th>
        </tr>
       <% @comments.each do |com| %>
        <tr>
          <td>
            <%= com.user.to_s%> commented <p id="user_comment"><%= com.comment%></p>
          </td>
        </tr>
       <% end %>
      </table>
    <% end %>
    </div>
  </div>
</div>

app/views/articles/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-backdrop="static"
     data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/articles/_form.html.erb
    <%= form_for([@user, @article]) do |f| %>

        <% if @article.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <%= f.label :title, class: "control-label col-sm-2" %>
          <div class="col-sm-10">
            <%= f.text_field :title,class: "form-control" %>
          </div>
        </div>
        <br/><br/>
        <div class="form-group">
          <%= f.label :body, class: "control-label col-sm-2" %>
          <div class="col-sm-10">
            <%= f.text_area :body, class: "form-control" %>
          </div>
        </div>
        <br/>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <br/>
             <%if @article.id.present? %>
            <%= f.submit "Update", class: "btn btn-primary"%>
             <%else%>
                <%= f.submit "Save", class: "btn btn-primary"%>

          <%end%>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit Article
  </div>
  <div class="panel-body">
    <%= render 'form' %>
    <br/><br/>
    <%= link_to 'Back', user_articles_path(@user.id) %>
  </div>
</div>

app/views/articles/index.html.erb
<%= render partial: 'dialog'%>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= @user.to_s%> Articles
    <div class="pull-right">
      <div class="glyphicon glyphicon-plus"></div>
      <%= link_to 'New Article', new_user_article_path %>
      <div class="glyphicon glyphicon-plus"></div>
      <%= link_to 'Add Cover Photo', edit_user_path(@user.id) %>
    </div>

  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @articles.each do |article| %>
          <tr>
            <td>
              <%= article.title %>
            </td>
            <td>
              <div class="glyphicon glyphicon-eye-open"></div>
              <%= link_to 'Show', "/users/#{@user.id}/articles/#{article.id}", :remote => true %>
            </td>
            <td>
              <div class="glyphicon glyphicon-edit"></div>
              <%= link_to 'Edit', "/users/#{@user.id}/articles/#{article.id}/edit" %>
            </td>
            <td>
              <div class="glyphicon glyphicon-remove"></div>
              <%= link_to 'Destroy', "/users/#{@user.id}/articles/#{article.id}", :method => :delete, :data => { :confirm => 'Are you sure?' } %>
            </td>
            <td>
              <div class="glyphicon glyphicon-tasks"></div>
              <%= link_to 'Add Comments', "/articles/#{article.id}/comments/new?user_id=#{@user.id}", :remote => true %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/articles/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    New Article
  </div>
  <div class="panel-body">
    <%= render 'form' %>
    <br/><br/>
    <%= link_to 'Back', user_articles_path(@user.id) %>
  </div>
</div>

app/views/articles/show.js.erb
$('#dialog h3').html("<i class='glyphicon'></i> Article Details");
$(".modal-body").html("<%= escape_javascript(render partial: 'article', locals: { article: @article} ) %>");

$('#dialog').modal("show");

app/views/comments/_new.html.erb
<%= form_for([@article, @comment]) do |f| %>

    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% @comment.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :comment, class: "control-label col-sm-2" %>
          <div class="col-sm-10">
            <%= f.text_area :comment,class: "form-control" %>
          </div>
        </div>
        <br/><br/>
        <%= f.hidden_field :user_id, :value => @user_id%>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <br/>
                <%= f.submit "Save", class: "btn btn-primary"%>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/comments/new.js.erb
$('#dialog h3').html("<i class='glyphicon'></i> Add Comment");
$(".modal-body").html("<%= escape_javascript(render partial: 'new', locals: { article: @article} ) %>");

$('#dialog').modal("show");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuthenticateWithoutGem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<script>
$(document).ready(function(){
    var imageUrl=$(".derby-home-display-bg").val();
var imageUrl=$(".derby-home-display-bg").val();
$('.new-profile').css('background-image', 'url(' + imageUrl + ')');
$('.new-profile').css('background-size', '100% 100%');
$('.new-profile').css('background-repeat', 'no-repeat');

});
</script>
<%if current_user.nil?%>
    <input class="derby-home-display-bg" type="hidden" value="/assets/bg.png"/>
<%else%>
    <input class="derby-home-display-bg" type="hidden" value="<%= @user.cover_photo.url%>"/>
<%end%>
<body 	<%if !current_user.nil?%>class="new-profile"<% end %> >
<%= render partial: "shared/header" %>
<div class="page_content">
  <div class="container">
  <%= yield %>
 </div>
</div>
<%= render partial: "shared/footer" %>
</body>

</html>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="row">
      <hr/>
      <div class="tleft" style="margin-left: 18px;">
        &copy; 2015 User Blog
      </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <!--/ place your website logo here
      -->
      <a class="navbar-brand" href="<%= root_path %>">
        <div class="glyphicon glyphicon-education"></div>
        User Blog
      </a>
    </div>
    <div class="pull-right twitter_btn">
          <div id="user_header">
            <% if current_user %>
                Logged in as <%= current_user.to_s %>.
                <%= link_to "Log Out", logout_path, class: "btn btn-primary " %>
            <% else %>
                <%= link_to "Sign Up", signup_path, class: "btn btn-primary " %>
                <%= link_to "Log In", login_path ,class: "btn btn-primary " %>
            <% end %>
         </div>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-body">
      <% unless flash.nil? %>

      <% flash.each do |key, value| %>
          <%if key == "error"%>
              <div class="alert alert-danger"><%= value %></div>
          <%else%>
              <div class="alert alert-success"><%= value %></div>
          <%end%>
      <% end %>
      <% end %>

      <%= form_for @user, :html => {class: 'form-horizontal' } do |f| %>
   <div class="row">
    <div class="col-md-10">
    <div class="form-group">
      <%= f.label :cover_photo, class: "control-label col-sm-2"%>
      <div class="col-sm-10">
        <%= f.file_field :cover_photo, accept: 'image/png,image/gif,image/jpeg'%>      </div>
    </div>
          <br/>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Upload", class: "btn btn-primary"%>
      </div>
    </div>
     </div>
    </div>
    <% end %>
      <%= link_to 'Back', user_articles_path(@user.id) %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% flash.each do |key, value| %>
    <%if key == "error"%>
        <div class="alert alert-danger"><%= value %></div>
    <%else%>
        <div class="alert alert-success"><%= value %></div>
    <%end%>
<% end %>

  <div class="row">
    <div class="col-md-12 bgimage">
      <div class="bgimage-inside"></div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>   <br/>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-body">
      <% if @user.errors.any? %>

          <div class="alert alert-danger">
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
<%= form_for @user, :html => {class: 'form-horizontal' } do |f| %>
   <div class="row">
    <div class="col-md-10">
    <div class="form-group">
      <%= f.label :first_name, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :first_name,class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :last_name, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :email, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.password_field :password,class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, class: "control-label col-sm-2" %>
      <div class="col-sm-10">
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
          <br/>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "SignUp", class: "btn btn-primary"%>
      </div>
    </div>
     </div>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-success"><%= value %></div>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-body">

      <%if @user.articles.blank?%>
      <%else%>

      <%end%>
    </div>
  </div>
</div>